#coding=utf-8

RMSYSTEM_LOGFILE='/var/log/raceman/raceman.log'

FO_RACEDETECTOR_SUBSCRIBE_TIMER=10
FO_RACEDETECTOR_HB_TIMER=10
FO_ANNOUNCE_PERIOD=30
FO_USERAGENT='Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0'  
FO_CLIENTPROTO='1.5'


#RMSound configuration 
RMS_SOUND_DIR='/opt/raceman/sounds/'
RMS_SOUND_TTS_DIR='/opt/raceman/sounds_tts/'

RMS_CHANNEL_BGM=0
RMS_CHANNEL_TICKER=1
RMS_CHANNEL_SYSTEM=2
RMS_CHANNEL_TARGET=3
RMS_CHANNEL_OTHER=4
RMS_RESERVED_CHANNELS=RMS_CHANNEL_OTHER+1
RMS_NUM_CHANNELS=RMS_RESERVED_CHANNELS+5
RMS_SDL_AUDIODRIVER='pulse'
RMS_SDL_AUDIOFILE='/dev/stdout'
RMS_FREQUENCY=22000
RMS_PYGAME_SAMPLESIZE=-16
RMS_PYGAME_SAMPLECHANNELS=1
RMS_PYGAME_FREQUENCY=8000
RMS_FILE_EXTENSION='ogg'

#Sounds
#SOUND_STARTSTOP='gong.wav'
SOUND_STARTSTOP=''
#SOUND_BGM='taxi.wav'
SOUND_BGM=''
SOUND_ACHIEVE='achv.ogg'
SOUND_LOST='boo.ogg'
SOUND_GOOD='peew.ogg'
SOUND_BAD='zzz.ogg'

# tts cache directory
TTS_CACHE_DIR='/var/cache/raceman'

#tts_festival configuration
TTS_FESTIVAL_COMMAND=u"(tts_textall \"%s\" \'file)(quit)\n"
TTS_FESTIVAL_SERVER_HOST='127.0.0.1'
TTS_FESTIVAL_SERVER_PORT=1314
TTS_FESTIVAL_BUFFER_SIZE=10*44100*2

# SAPI configuration
TTS_SAPI_SERVER_HOST='192.168.56.102'
TTS_SAPI_SERVER_PORT=40040
TTS_SAPI_BUFFER_SIZE=10*44100*2

# should be in profile soon
RMS_SOUND_THEME='.'
RMS_BGM_VOLUME=0.2

#Do not delete
track=None
profile=None
target=None
rival=None